### ISSUE TITLE
Treffen nächste Woche

### ISSUE THREAD

**Issue by krakowski** [ProPra16/programmierpraktikum-abschlussprojekt-unicorndefenders#1]
Hey Gruppe,

wir Tutoren wurden angewiesen uns im Idealfall einmal die Woche mit euch zu treffen.
Beim Treffen selbst könnt ihr beispielsweise Verständnisfragen zum Projekt oder allgemeine
Fragen zur Implementierung stellen. Das ganze sollte nicht länger als eine halbe Stunde dauern, jedoch
kann ich auch länger bleiben wenn ich gerade nichts zu tun hab und es erwünscht ist.

Für die Terminauswahl habe ich unter folgendem Link ein Doodle erstellt, bei dem ihr euren
Gruppennamen angeben und einen Termin auswählen sollt:

[http://doodle.com/poll/9wqkbsk8b7rt5hci](http://doodle.com/poll/9wqkbsk8b7rt5hci)

Insgesamt gibt es 16 Termine, es sollte sich also etwas finden.
Bei Fragen könnt ihr einfach hier im Issue antworten, ich werde dann per Mail benachrichtigt.

Viele Grüße,
Filip

**Comment by krakowski** [comment]
Hey,

habe gerade gesehen, dass ihr Montag 13:30 ausgewählt habt.
um 12:30 treffe ich mich mit der ersten Gruppe in Raum 25.22.00.72.
Da der Raum bis 16:30 frei sein sollte schlage ich vor, dass wir uns da treffen.

Viele Grüße,
Filip

**Comment by eyoez100** [comment]
Am 2016-07-04 02:02, schrieb Filip Krakowski:

> Hey,
> 
> habe gerade gesehen, dass ihr Montag 13:30 ausgewählt habt.
> um 12:30 treffe ich mich mit der ersten Gruppe in Raum 25.22.00.72.
> Da der Raum bis 16:30 frei sein sollte schlage ich vor, dass wir uns da 
> treffen.
> 
> Viele Grüße,
> Filip
> 
> ---
> 
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub:
> https://github.com/ProPra16/programmierpraktikum-abschlussprojekt-unicorndefenders/issues/1#issuecomment-230183356
> Okay, machen wir so.

Bis dann!
